### ISSUE TITLE
Godot 4?

### ISSUE THREAD

**Issue by flth** [moonbench/simple-godot-train#1]
Is there any chance this demo can be update to Godot 4? 
Total beginner here and not able to convert it to Godot 4 :(

**Comment by Anniepoo** [comment]
I'd also be interested in converting it to Godot 4.  @moonbench , any interest in doing a communal hack some time?

**Comment by flth** [comment]
I've found one in the forks, going to check this out https://github.com/RJSzynal/simple-godot-train

**Comment by moonbench** [comment]
Sorry for not responding sooner.

I've been meaning to make an updated Godot 4 version. There's a number of improvements that can be added with the latest engine version. I'll try and started on that this weekend, hopefully it goes quickly enough.

> I'd also be interested in converting it to Godot 4. @moonbench , any interest in doing a communal hack some time?

Sounds fun!

**Comment by moonbench** [comment]
@flth I've started a `godot-4-upgrade` branch (https://github.com/moonbench/simple-godot-train/tree/godot-4-upgrade) that seems to be in a working state now, with as much of a 1:1 conversion as possible.

**Comment by moonbench** [comment]
Closing this issue as `done` since the godot4 branch has been merged into the master branch 🎉
